# docker-compose.yml
version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: tail -f /dev/null
    volumes:
      - ../..:/workspaces:cached
